[[BOOKMARK-API]]
== 북마크 API

'''

=== 북마크 등록

operation::/bookmark-docs-controller/북마크_등록_api/[snippets='http-request,request-fields,http-response,response-fields']

=== 북마크 수정

operation::/bookmark-docs-controller/북마크_수정_api/[snippets='http-request,path-parameters,request-fields,http-response']

=== 북마크 삭제

operation::/bookmark-docs-controller/북마크_삭제_api/[snippets='http-request,path-parameters,http-response']

=== 내 북마크 목록 조회

operation::/bookmark-docs-controller/내_북마크_목록_조회_api/[snippets='http-request,request-parameters,http-response,response-fields']

=== 다른 사람 북마크 목록 조회

operation::/bookmark-docs-controller/다른_사람_북마크_목록_조회_api/[snippets='http-request,path-parameters,request-parameters,http-response,response-fields']

=== 피드 북마크 목록 조회

operation::/피드_북마크_조회/피드_북마크_조회_api/[snippets='http-request,request-parameters,http-response,response-fields']

=== url 중복 확인 요청

operation::/bookmark-docs-controller/url_중복확인_api/[snippets='http-request,request-parameters,http-response,response-fields']
