spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://linkocean-dev-rds.czvbgr7hie3i.ap-northeast-2.rds.amazonaws.com:3306/linkocean?serverTimezone=UTC&characterEncoding=UTF-8"
    username: "root"
    password: "root1234"
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: "jdbc:mysql://linkocean-dev-rds.czvbgr7hie3i.ap-northeast-2.rds.amazonaws.com:3306/linkocean?serverTimezone=UTC&characterEncoding=UTF-8"
    user: root
    password: root1234
