[[Boomark-API]]
== 북마크 API

'''

=== 북마크 등록

operation::/bookmark-rest-docs-test/북마크_등록_api/[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 내 북마크 목록 조회

operation::/bookmark-rest-docs-test/내_북마크_목록_조회_api/[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 다른 사람 북마크 목록 조회

operation::/bookmark-rest-docs-test/다른_사람_북마크_목록_조회_api[snippets='http-request,request-headers,path-parameters,request-parameters,http-response,response-fields']

=== 피드 북마크 목록 조회

operation::/bookmark-rest-docs-test/피드_북마크_조회_api/[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 북마크 상세 조회

operation::/bookmark-rest-docs-test/북마크_상세_조회_api/[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== 북마크 업데이트

operation::/bookmark-rest-docs-test/북마크_업데이트_api/[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 북마크 삭제

operation::/bookmark-rest-docs-test/북마크_삭제_api/[snippets='http-request,request-headers,path-parameters,http-response']

=== 북마크 공유 알림

operation::/bookmark-rest-docs-test/북마크_공유_알림_api/[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 중복 Url 확인

operation::/bookmark-rest-docs-test/중복_url_확인_api/[snippets='http-request,request-headers,request-parameters,http-response,response-fields']
